name: Update portfolio grid

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate portfolio grid
        run: |
          echo '<table>' > portfolio-grid.md
          i=0
          for img in portfolio/*.{png,PNG,jpg,JPG,jpeg,JPEG,gif,GIF}; do
            [ -e "$img" ] || continue
            if [ $((i % 3)) -eq 0 ]; then echo '<tr>' >> portfolio-grid.md; fi
            echo "<td><img src=\"$img\" width=\"200\"></td>" >> portfolio-grid.md
            if [ $((i % 3)) -eq 2 ]; then echo '</tr>' >> portfolio-grid.md; fi
            i=$((i + 1))
          done
          if [ $((i % 3)) -ne 0 ]; then echo '</tr>' >> portfolio-grid.md; fi
          echo '</table>' >> portfolio-grid.md

      - name: Update README.md
        run: |
          sed -i '/<!-- PORTFOLIO-START -->/,/<!-- PORTFOLIO-END -->/{
            /<!-- PORTFOLIO-START -->/r portfolio-grid.md
            /<!-- PORTFOLIO-START -->/!{/<!-- PORTFOLIO-END -->/!d}
          }' README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Auto-update portfolio grid" || echo "No changes to commit"
          git push
