name: Update Portfolio Grid

on:
  push:
    paths:
      - "portfolio/**"   # run only when images are added/changed in portfolio folder
  workflow_dispatch:      # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate portfolio grid
        run: |
          echo "<!-- PORTFOLIO-START -->" > portfolio_section.md
          echo "<div align='center'>" >> portfolio_section.md
          count=0
          for img in portfolio/*.png; do
            raw_url="https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/main/$img"
            echo "<img src=\"$raw_url\" width=\"250\" style=\"margin:10px;\">" >> portfolio_section.md
            count=$((count+1))
            if [ $((count % 3)) -eq 0 ]; then
              echo "<br>" >> portfolio_section.md
            fi
          done
          echo "</div>" >> portfolio_section.md
          echo "<!-- PORTFOLIO-END -->" >> portfolio_section.md

      - name: Update README
        run: |
          sed -i '/<!-- PORTFOLIO-START -->/,/<!-- PORTFOLIO-END -->/c\<!-- PORTFOLIO-START -->\n'"$(cat portfolio_section.md)"'\n<!-- PORTFOLIO-END -->' README.md

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update portfolio grid" || echo "No changes to commit"
          git push
